### ISSUE TITLE
OperationError: failed to decode public key | Encryption not working

### ISSUE THREAD

**Issue by LioXP** [PeterBielak/OpenCrypto#42]
Hello. I am trying to encrypt a message with a RSA public Key, but i always get an error.
The error:
```
error: Uncaught (in promise) OperationError: failed to decode public key
    at async encrypt (ext:deno_crypto/00_crypto.js:4539:26)
    at async SubtleCrypto.encrypt (ext:deno_crypto/00_crypto.js:538:12)
```
I am running deno, which is fully compatible with the SubtleCrypto API.

My code:

```ts
export function encrypt(public_key_pem: string, data: string) {
  const crypt = new (OpenCrypto as any as typeof OpenCrypto)();
  console.log(public_key_pem);
  crypt
    .pemPublicToCrypto(public_key_pem, {
      name: "RSA-OAEP",
      hash: "SHA-512",
      usages: ["encrypt", "wrapKey"],
      isExtractable: false,
    })
    .then((public_key: CryptoKey) => {
      const input = crypt.stringToArrayBuffer(data);
      crypt.rsaEncrypt(public_key, input).then((encryptedData: string) => {
        console.log(encryptedData);
      });
    });
}
```
data is a string, for example "Text".
public_key_pem is a public Key, which i am storing in a file. I am reading it using the following code, and then calling the "encrypt" function which i pasted above.

```
const public_key_pem = fs
      .readFileSync(public_key_path)
      .toString();
```

The public key file looks like this:

```
-----BEGIN PUBLIC KEY-----
MIID4jANBgkqhkiG9w0BAQEFAAOCA88AMIIDygKCA8EAtexSLlasbFT7rPht2UsS
Kd7tJaVMpD0JFFh0RLXOW6OBJFQ98W9h9OlwINFa4FpoPJooDz4TZkfO29/r2+1B
JZ0CrFNCmtIUdlkJii1Lr7gNChNCgfm/Lo/+TMdw6JnvWRYIXBF8qc+RTrMfPUzs
gRQaUptXeFt4TNdKI9jPimAfXs1Y0bIOJBtJDc12cvCAUbToJhG4WK4hcWM7Jhvh
WF7rKPW29jT3cgj2VNgp1IErw2a4rS5NXjCjV5h1Rz2j+m3EffLKcGUV9ubDvo7d
zfmaqrkb1DOVYZ1ekge/MeZ7PyYfGd/ITYH8rhr7rN2oy3O/vvJBvZQwkQpvRj1J
xOIT5Prg+Oql/aV2b9ixOXG+Ra9+i+oJMOGZ/7EviO+8l7RcZWOS7XLl84XoQN1d
oDU2aSoHmORlJ5SPPjMNYKhzUtpcgWkpq9Rvb5a1NBi4wUez7IQnrDO7SEWr/7r3
kfzx5dGIm5maLq14YgQv3lg1vZVh5iRmU4T4uYmwdqA/gTsZPQMtYqW9lH41ZQ3k
SC1v/J2pPT77xDhDYYaxcMY0SFrET/p/XklxKsly1SezlAWpo6MVwRt7QCwdTg4Y
DaSlWTXdiMvS6wREHapjVwcSS0B7+jpFAdrlwmGpkV0GcgaM9wHJT+ZqKth98gk6
oqgyrmFT/RGMDyPjtdGfW96qSV0CJbgIenP/umviig9dDjbchacoObe6VVjjkAqI
Y8BmU5Vo2cSJCESqefDoYPElX14pd/MNyKoET3DQFHN3P4gj12yOLcLQGtrmvn4r
9RaWjgkZuaphoeGlI6zcN5VZ4jaecd2xlWmKU/H/pz3ePJax3h+8qCs+nBFKaWOi
n0PM6/+zSsaOn52Bn0xy02GrZFNzugG+yGSP55X8f1O/ouqOdob/Ev4tEwuBfgVR
vee+YisoPh6kbNrJnUZSuciuDI0lKtOP5QrXeG4NU2sq4eyk5W3131BC1XEVcfbS
1aIZjtxPLVpLAHampe+C8D+LYJPzp8I7ogxJ8FjKhjNH39ZzX+QcoaVrQEBGF6FR
qroP+BFKHjLm41XRYqcFSIqqZCXqqtMjdnopMHFa1SbMXhprTWHUSxenaJWcp2ei
qpZ4N6HFHTf/XfTiJLYlIaRIaufGG8/bObsRrcbKMwA4OEykVo1KwfNVQxEhxsP9
yMQud5xunpHWy7KFvSTLRSVfYscfF59/aJBl+IYEvIGWep+pUoatYBB1Fg9+8qTP
rbLmvKltQF5rybfzDCsi4UB/Bybo9OqaHsScwGqX8tOPAgMBAAE=
-----END PUBLIC KEY-----
```

**Comment by LioXP** [comment]
I fixed it by using a key size, which doesn't exceed 4096 bits. 👍
